// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Z4icBZ0CZnTrQKFkMVXyyh9i79qRQYk',
    appId: '1:970352894039:web:3bc1a1550872618b118312',
    messagingSenderId: '970352894039',
    projectId: 'greatbro-it',
    authDomain: 'greatbro-it.firebaseapp.com',
    storageBucket: 'greatbro-it.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5Ud_AsLpd0TyT8_KhegJLlgtb54AXQY',
    appId: '1:970352894039:android:18bd1c57bcee4f55118312',
    messagingSenderId: '970352894039',
    projectId: 'greatbro-it',
    storageBucket: 'greatbro-it.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQPQ578UMi3jczeG93X1ox8Q1KS8h_rE',
    appId: '1:970352894039:ios:8162b2354a4f039b118312',
    messagingSenderId: '970352894039',
    projectId: 'greatbro-it',
    storageBucket: 'greatbro-it.appspot.com',
    iosBundleId: 'com.example.greatbroIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPQPQ578UMi3jczeG93X1ox8Q1KS8h_rE',
    appId: '1:970352894039:ios:0f4e9cf5f41d1637118312',
    messagingSenderId: '970352894039',
    projectId: 'greatbro-it',
    storageBucket: 'greatbro-it.appspot.com',
    iosBundleId: 'com.example.greatbroIt.RunnerTests',
  );
}
